server:
  port: 8090
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/littlenews?useUnicode=true&charactorEncoding=utf-8&serverTimezone=UTC
mybatis:
  type-aliases-package: com.teskinfly.mapper
  mapper-locations: ./mybatis/mapper/*.xml
